import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import fs from 'fs';
import path from 'path';

function capitalize(word: string) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

const docsDir = path.join(__dirname, 'docs');
const folders = fs
  .readdirSync(docsDir, { withFileTypes: true })
  .filter(dirent => dirent.isDirectory())
  .map(dirent => dirent.name);

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Admin',
      link: { type: 'doc', id: 'admin/intro' },
      items: [{ type: 'autogenerated', dirName: 'admin' }],
    },
    {
      type: 'category',
      label: 'Parent',
      link: { type: 'doc', id: 'parent/intro' },
      items: [{ type: 'autogenerated', dirName: 'parent' }],
    },
  ],
  };

export default sidebars;
